### ISSUE TITLE
Example parsing fails if input_data is different for Part 1 and Part 2

### ISSUE THREAD

**Issue by paulsuh** [wimglenn/aocd-example-parser#4]
At least for 2023.01, my example data has 

```1abc2
pqr3stu8vwx
a1b2c3d4e5f
treb7uchet
```

and 

```two1nine
eightwothree
abcone2threexyz
xtwone3four
4nineeightseven2
zoneight234
7pqrstsixteen 
```

This means that there needs to be two sets of input_data for the examples. From the code it looks like the example data is always taken from the first part. 

I've forked the repo and I'm going to take a swing at fixing this. Question is how to return the new input_data. I think the best way is to return two Examples in the list Puzzle.examples. The first one will have the Part 1 input_data, answer_a, and answer_b. The second one will have the Part 2 input_data, answer_a, and answer_b. This will ensure that any existing code that depends on Puzzle.examples[0].<something> will continue to work. Using the second set of example input data only requires using Puzzle.examples[1] in place of [0]. 

Thoughts?

**Comment by wimglenn** [comment]
Yes, returning a list of two examples from `puzzle.examples` is the correct approach here.  Also, for this particular case, the `answer_b` for part a should be `None` and so should the `answer_a` for part b.

**Comment by wimglenn** [comment]
Closing because this is already fixed in [current releases](https://pypi.org/project/aocd-example-parser/#history)
