### ISSUE TITLE
Parsed answer for the second part of day 1 in 2024 is wrong

### ISSUE THREAD

**Issue by bfontaine** [wimglenn/aocd-example-parser#7]
Hello,

When parsing the text for the second part of the day 1 of this year, we get:
```
>>> aocd.models.Puzzle(day=1, year=2024).examples
[Example(input_data='3   4\n4   3\n2   5\n1   3\n3   9\n3   3', answer_a='11', answer_b='9', extra=None)]
```

However, this `answer_b` should be `31`, not `9`:
```html
<p>So, for these example lists, the similarity score at the end of this process is <code><em>31</em></code> (<code>9 + 4 + 0 + 0 + 9 + 9</code>).</p>
```

**Comment by baptistecottier** [comment]
Hello, 
As said in the repo description:
> the goal is to maximize the probability that your parser will somehow find the right result at the instant a new puzzle unlocks.

Then, the parser sometimes fails. Either you can wait for the examples.json file to be updated, or you can manually rectify it by including this (making examples correct until day 5).

<pre><code>"2024/01": [
    {
      "answer_b":   "b_code[-2] "
    }
  ],
  "2024/03": [
    {
      "answer_a":   "a_code[-3] ",
      "answer_b":   "None"
    },
    {
      "input_data": "b_code[-8]",
      "answer_a":   "None",
      "answer_b":   "b_code[-2] "
    }
  ], 
  "2024/04":  [
    {
      "input_data": "a_code[-7]",
      "answer_a":   "a_code[-5]",
      "answer_b":   "b_code[-2]"
    }
  ]</code></pre>

**Comment by bfontaine** [comment]
…Or we can fix the parser? I’m not familiar with the code, but in the HTML snippet above the expected result is in `<code><em></em></code>`, but for some reason the parser extracts the last number that’s inside a `<code>`.

**Comment by wimglenn** [comment]
The reference locators have been updated in a [recent release](https://pypi.org/project/aocd-example-parser/2024.12.24/)

```bash
$ aocd 2024 1 -e
                       --- Day 1: Historian Hysteria ---                        
                      https://adventofcode.com/2024/day/1                       
------------------------------- Example data 1/1 -------------------------------
3   4
4   3
2   5
1   3
3   9
3   3
--------------------------------------------------------------------------------
answer_a: 11
answer_b: 31
--------------------------------------------------------------------------------
```
